/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBBTCAllocatorInterface extends ethers.utils.Interface {
  functions: {
    "addToken(address,address,uint256)": FunctionFragment;
    "deployLimitFor(address)": FunctionFragment;
    "deployedFor(address)": FunctionFragment;
    "deposit(address,uint256)": FunctionFragment;
    "depositToTreasury()": FunctionFragment;
    "enableDepositToTreasury()": FunctionFragment;
    "exceedsLimit(address,uint256)": FunctionFragment;
    "harvest()": FunctionFragment;
    "harvestFor(address[])": FunctionFragment;
    "lowerLimit(address,uint256)": FunctionFragment;
    "newLimit(address)": FunctionFragment;
    "policy()": FunctionFragment;
    "pullManagement()": FunctionFragment;
    "pushManagement(address)": FunctionFragment;
    "queueRaiseLimit(address,uint256)": FunctionFragment;
    "raiseLimit(address)": FunctionFragment;
    "raiseLimitTimelockEnd(address)": FunctionFragment;
    "referralCode()": FunctionFragment;
    "renounceManagement()": FunctionFragment;
    "revertDepositToTreasury()": FunctionFragment;
    "rewardsPending(address)": FunctionFragment;
    "rewardsPendingFor(address[],address)": FunctionFragment;
    "setReferralCode(uint16)": FunctionFragment;
    "timelockInBlocks()": FunctionFragment;
    "totalValueDeployed()": FunctionFragment;
    "vaultTokenRegistry(address)": FunctionFragment;
    "vaultTokens(uint256)": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployLimitFor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "deployedFor", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableDepositToTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exceedsLimit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "harvest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "harvestFor",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "lowerLimit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "newLimit", values: [string]): string;
  encodeFunctionData(functionFragment: "policy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pullManagement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushManagement",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "queueRaiseLimit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "raiseLimit", values: [string]): string;
  encodeFunctionData(
    functionFragment: "raiseLimitTimelockEnd",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "referralCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceManagement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertDepositToTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardsPending",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardsPendingFor",
    values: [string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralCode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockInBlocks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalValueDeployed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaultTokenRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployLimitFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableDepositToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exceedsLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "harvestFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lowerLimit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newLimit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pullManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueRaiseLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "raiseLimit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseLimitTimelockEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertDepositToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardsPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardsPendingFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockInBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValueDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultTokenRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "OwnershipPulled(address,address)": EventFragment;
    "OwnershipPushed(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipPulled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipPushed"): EventFragment;
}

export type OwnershipPulledEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type OwnershipPushedEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class IBBTCAllocator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBBTCAllocatorInterface;

  functions: {
    addToken(
      token: string,
      vaultToken: string,
      max: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployLimitFor(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deployedFor(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    deposit(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositToTreasury(overrides?: CallOverrides): Promise<[boolean]>;

    enableDepositToTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exceedsLimit(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    harvest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    harvestFor(
      _vaultTokens: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lowerLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newLimit(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    policy(overrides?: CallOverrides): Promise<[string]>;

    pullManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushManagement(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    queueRaiseLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    raiseLimit(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    raiseLimitTimelockEnd(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    referralCode(overrides?: CallOverrides): Promise<[number]>;

    renounceManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revertDepositToTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewardsPending(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rewardsPendingFor(
      tokens: string[],
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setReferralCode(
      code: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    timelockInBlocks(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalValueDeployed(overrides?: CallOverrides): Promise<[BigNumber]>;

    vaultTokenRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    vaultTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    withdraw(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addToken(
    token: string,
    vaultToken: string,
    max: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployLimitFor(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  deployedFor(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  deposit(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositToTreasury(overrides?: CallOverrides): Promise<boolean>;

  enableDepositToTreasury(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exceedsLimit(
    token: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  harvest(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  harvestFor(
    _vaultTokens: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lowerLimit(
    token: string,
    newMax: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newLimit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  policy(overrides?: CallOverrides): Promise<string>;

  pullManagement(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushManagement(
    newOwner_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  queueRaiseLimit(
    token: string,
    newMax: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  raiseLimit(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  raiseLimitTimelockEnd(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  referralCode(overrides?: CallOverrides): Promise<number>;

  renounceManagement(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revertDepositToTreasury(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewardsPending(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  rewardsPendingFor(
    tokens: string[],
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setReferralCode(
    code: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  timelockInBlocks(overrides?: CallOverrides): Promise<BigNumber>;

  totalValueDeployed(overrides?: CallOverrides): Promise<BigNumber>;

  vaultTokenRegistry(arg0: string, overrides?: CallOverrides): Promise<string>;

  vaultTokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  withdraw(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addToken(
      token: string,
      vaultToken: string,
      max: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deployLimitFor(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    deployedFor(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositToTreasury(overrides?: CallOverrides): Promise<boolean>;

    enableDepositToTreasury(overrides?: CallOverrides): Promise<void>;

    exceedsLimit(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    harvest(overrides?: CallOverrides): Promise<void>;

    harvestFor(
      _vaultTokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    lowerLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    newLimit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    policy(overrides?: CallOverrides): Promise<string>;

    pullManagement(overrides?: CallOverrides): Promise<void>;

    pushManagement(newOwner_: string, overrides?: CallOverrides): Promise<void>;

    queueRaiseLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    raiseLimit(token: string, overrides?: CallOverrides): Promise<void>;

    raiseLimitTimelockEnd(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    referralCode(overrides?: CallOverrides): Promise<number>;

    renounceManagement(overrides?: CallOverrides): Promise<void>;

    revertDepositToTreasury(overrides?: CallOverrides): Promise<void>;

    rewardsPending(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    rewardsPendingFor(
      tokens: string[],
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setReferralCode(
      code: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    timelockInBlocks(overrides?: CallOverrides): Promise<BigNumber>;

    totalValueDeployed(overrides?: CallOverrides): Promise<BigNumber>;

    vaultTokenRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    vaultTokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    withdraw(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipPulled(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipPulled(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "OwnershipPushed(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipPushed(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    addToken(
      token: string,
      vaultToken: string,
      max: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployLimitFor(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    deployedFor(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositToTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    enableDepositToTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exceedsLimit(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    harvest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    harvestFor(
      _vaultTokens: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lowerLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newLimit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    policy(overrides?: CallOverrides): Promise<BigNumber>;

    pullManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushManagement(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    queueRaiseLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    raiseLimit(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    raiseLimitTimelockEnd(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    referralCode(overrides?: CallOverrides): Promise<BigNumber>;

    renounceManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revertDepositToTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewardsPending(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    rewardsPendingFor(
      tokens: string[],
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setReferralCode(
      code: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    timelockInBlocks(overrides?: CallOverrides): Promise<BigNumber>;

    totalValueDeployed(overrides?: CallOverrides): Promise<BigNumber>;

    vaultTokenRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vaultTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addToken(
      token: string,
      vaultToken: string,
      max: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployLimitFor(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployedFor(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositToTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    enableDepositToTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exceedsLimit(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    harvest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    harvestFor(
      _vaultTokens: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lowerLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newLimit(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    policy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pullManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushManagement(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    queueRaiseLimit(
      token: string,
      newMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    raiseLimit(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    raiseLimitTimelockEnd(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    referralCode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revertDepositToTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewardsPending(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rewardsPendingFor(
      tokens: string[],
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setReferralCode(
      code: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    timelockInBlocks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalValueDeployed(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaultTokenRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaultTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
