/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CitadelAccessControlled,
  CitadelAccessControlledInterface,
} from "../CitadelAccessControlled";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract ICitadelAuthority",
        name: "authority",
        type: "address",
      },
    ],
    name: "AuthorityUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "authority",
    outputs: [
      {
        internalType: "contract ICitadelAuthority",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ICitadelAuthority",
        name: "_newAuthority",
        type: "address",
      },
    ],
    name: "setAuthority",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CitadelAccessControlled__factory {
  static readonly abi = _abi;
  static createInterface(): CitadelAccessControlledInterface {
    return new utils.Interface(_abi) as CitadelAccessControlledInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CitadelAccessControlled {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CitadelAccessControlled;
  }
}
