/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IsCTDLOLD, IsCTDLOLDInterface } from "../IsCTDLOLD";

const _abi = [
  {
    inputs: [],
    name: "INDEX",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IsCTDLOLD__factory {
  static readonly abi = _abi;
  static createInterface(): IsCTDLOLDInterface {
    return new utils.Interface(_abi) as IsCTDLOLDInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IsCTDLOLD {
    return new Contract(address, _abi, signerOrProvider) as IsCTDLOLD;
  }
}
